services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ressources
    volumes:
       - data:/var/lib/postgresql/data
    ports:
      - "21500:5432"

volumes:
  data: